config/routes.rb
Rails.application.routes.draw do
  resources :contatosses
  resources :telefones
  resources :contatos
  resources :rooms

  get '/index', to: 'contatos#index'
  get '/visualizando', to: 'contatos#visualizando'

  get '/indexCalculadora', to: 'calculadora#indexCalculadora'
  post '/indexCalculadora', to: 'calculadora#indexCalculadora'

  #post '/show', to: 'contatos#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/contatoss.rb
class Contatoss < ApplicationRecord
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  def visualizando
    @contatos = Contato.order(:nome).last
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato Criado com Sucesso.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato Alterado com Sucesso.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato Deletado com Sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :endereco, :email, :dataNascimento)
    end

end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/_form.html.erb
      <%= form_with(model: contato, local: true) do |form| %>
        <% if contato.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

            <ul>
            <% contato.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

    <form class="form-inline">
      <div class="form-group row">
        <label class="col-md-4 control-label" for="formGroupInputLarge">Nome</label>
        <div class="col-xs-8">
            <%= form.text_field :nome, id: :contato_nome, class: 'form-control' %>
        </div>
      </div>
      
      <div class="form-group row">
        <label class="col-md-4 control-label" for="formGroupInputLarge">Endereço</label>
          <div class="col-xs-8">
            <%= form.text_field :endereco, id: :contato_endereco, class: 'form-control' %>
          </div>
        </div>

      <div class="form-group row">
        <label class="col-md-6 control-label" for="formGroupInputLarge">E-Mail</label>
          <div class="col-xs-8">
            <%= form.text_field :email, id: :contato_email, class: 'form-control' %>
          </div>
      </div>

      <div class="form-group row">
          <label class="col-md-6 control-label" for="formGroupInputLarge">Data Nascimento</label>
          <div class="col-xs-8">
          <%= form.date_select :dataNascimento, id: :contato_dataNascimento, start_year: 1950, order: [:day, :month, :year], :use_month_names=>["Janeiro" ,"Fevereiro", "Março", "Abril" ,"Maio", "Junho","Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],  class: 'selectpicker'%>
         </div>
        </div>
    
    
  
      <div class="text-center">
        <div class="actions">
          <%= form.submit class: 'btn btn-success center-block'%>
          <%= link_to 'Voltar', contatos_path, class: "btn btn-link" %>
        </div>
      </div>

    </form>

  <% end %>
 

app/views/contatos/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Agenda SECITEC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
            <li class="nav-item">
             <h5> <a class="nav-link" href="#">Contato</a> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>


<br/>
<br/>
<br/>	

<h1>Editando Contato</h1>

<%= render 'form', contato: @contato, class: 'btn btn-success center-block' %>

<%= link_to 'Visualizar', @contato, class: "btn btn-link" %> |
<%= link_to 'Voltar', contatos_path, class: "btn btn-link" %>

 <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
     <h3 class="text-center text-white">Redes Sociais</h3>
     <a class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a>
    </div>
      <!-- /.container -->
   </footer>

app/views/contatos/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
  <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index">Agenda SECITEC</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
            <li class="nav-item">
             <h5> <a class="nav-link" href="#">Contato</a> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>


      <p id="notice"><%= notice %></p>

      <h1>Contatos</h1>

<div id="main-container" class="container-fluid">
     <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <div class="row">
           <tr>

         <div class="col-xs-6 col-md-4"><th>Nome</th></div>
         <div class="col-xs-6 col-md-4"><th>Endereco</th></div>
         <div class="col-xs-6 col-md-4"><th>E-mail</th></div>
         <div class="col-xs-8 col-md-4"><th>Data Nascimento</th></div>
         <div class="col-xs-6 col-md-4"><th colspan="3"></th></div>
          </div>

           </tr>
          </div>
        </thead>

        <tbody>
          <% @contatos.each do |contato| %>
           <div class="row">
            <tr>
             <div class="col-xs-6 col-md-4"> <td> <h6> <%= contato.nome %> </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td> <h6><%= contato.endereco %> </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td> <h6><%= contato.email %>  </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td> <h6><%= contato.dataNascimento %> </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td><%= link_to 'Visualizar', contato, class: "btn btn-link" %></td></div>
             <div class="col-xs-6 col-md-4"> <td><%= link_to 'Editar', edit_contato_path(contato), class: "btn btn-link" %></td></div>
             <div class="col-xs-6 col-md-4"> <td><%= link_to 'Deletar', contato, class: "btn btn-link", method: :delete, data: { confirm: 'Tem certezar que você quer deletar?' } %></td></div>

              </tr>
            </div>

          <% end %>
        </tbody>
       </table>
       </div>
      </div>
    </div>

      <div class="py-5 bg-dark">
          <div class="container-fluid">
              <h5 class="text-center">SECITEC</h5>
          </div>
      </div>

  </body>
</html>

app/views/contatos/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Agenda</title>
    <%= csrf_meta_tags %> 
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     </head>

<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index">Agenda SECITEC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
            <li class="nav-item">
             <h5> <a class="nav-link" href="#">Contato</a> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>


	<div class="container-fluid">
     <div class="row">
		<h1 class="text-center">Novo Contato</h1>
		<%= render 'form', contato: @contato, class: "btn btn-link" %>
		 </div>
		</div>

 <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
     <h3 class="text-center text-white">SECITEC</h3>
    </div>
      <!-- /.container -->
   </footer>

</body>
</html>

app/views/contatos/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index">Agenda SECITEC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
            <li class="nav-item">
             <h5> <a class="nav-link" href="#">Contato</a> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>


<br/>
<br/>
<br/>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @contato.endereco %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Data Nascimento:</strong>
  <%= @contato.dataNascimento %>
</p>

<%= link_to 'Editar', edit_contato_path(@contato), class: "btn btn-link" %>
<%= link_to 'Voltar', contatos_path, class: "btn btn-link" %>

<!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
       <h3 class="text-center text-white">Redes Sociais</h3>
       <a class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a>
      </div>
      <!-- /.container -->
    </footer>

app/views/contatos/visualizando.html.erb
<div id="main-container" class="container-fluid">
    <div class="row">
     <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <div class="row">
           <tr>

         <div class="col-xs-6 col-md-4"><th>Nome</th></div>
          </div>

           </tr>
          </div>
        </thead>

        <tbody>
          <% @contatos.each do |contato| %>
           <div class="row">
            <tr>
             <div class="col-xs-6 col-md-4"> <td> <h6> <%= contato.nome %> </h6></td></div>
              </tr>
            </div>

          <% end %>
        </tbody>
       </table>
       </div>
      </div>
    </div>