config/routes.rb
Rails.application.routes.draw do
  resources :contatosses
  resources :telefones
  resources :contatos
  resources :rooms

  get '/index', to: 'contatos#index'
  get '/visualizando', to: 'contatos#visualizando'

  get '/indexCalculadora', to: 'calculadora#indexCalculadora'
  post '/indexCalculadora', to: 'calculadora#indexCalculadora'

  #post '/show', to: 'contatos#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/contatosses_controller.rb
class ContatossesController < ApplicationController
  before_action :set_contatoss, only: [:show, :edit, :update, :destroy]

  # GET /contatosses
  # GET /contatosses.json
  def index
    @contatosses = Contatoss.all
  end

  # GET /contatosses/1
  # GET /contatosses/1.json
  def show
  end

  # GET /contatosses/new
  def new
    @contatoss = Contatoss.new
  end

  # GET /contatosses/1/edit
  def edit
  end

  # POST /contatosses
  # POST /contatosses.json
  def create
    @contatoss = Contatoss.new(contatoss_params)

    respond_to do |format|
      if @contatoss.save
        format.html { redirect_to @contatoss, notice: 'Contatoss was successfully created.' }
        format.json { render :show, status: :created, location: @contatoss }
      else
        format.html { render :new }
        format.json { render json: @contatoss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatosses/1
  # PATCH/PUT /contatosses/1.json
  def update
    respond_to do |format|
      if @contatoss.update(contatoss_params)
        format.html { redirect_to @contatoss, notice: 'Contatoss was successfully updated.' }
        format.json { render :show, status: :ok, location: @contatoss }
      else
        format.html { render :edit }
        format.json { render json: @contatoss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatosses/1
  # DELETE /contatosses/1.json
  def destroy
    @contatoss.destroy
    respond_to do |format|
      format.html { redirect_to contatosses_url, notice: 'Contatoss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contatoss
      @contatoss = Contatoss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contatoss_params
      params.require(:contatoss).permit(:nome, :endereco, :email, :dataNascimento)
    end
end

app/helpers/contatosses_helper.rb
module ContatossesHelper
end

app/views/contatosses/_form.html.erb
<%= form_with(model: contatoss, local: true) do |form| %>
  <% if contatoss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contatoss.errors.count, "error") %> prohibited this contatoss from being saved:</h2>

      <ul>
      <% contatoss.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :contatoss_nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco, id: :contatoss_endereco %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contatoss_email %>
  </div>

  <div class="field">
    <%= form.label :dataNascimento %>
    <%= form.date_select :dataNascimento, id: :contatoss_dataNascimento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contatosses/edit.html.erb
<h1>Editing Contatoss</h1>

<%= render 'form', contatoss: @contatoss %>

<%= link_to 'Show', @contatoss %> |
<%= link_to 'Back', contatosses_path %>

app/views/contatosses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Email</th>
      <th>Datanascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatosses.each do |contatoss| %>
      <tr>
        <td><%= contatoss.nome %></td>
        <td><%= contatoss.endereco %></td>
        <td><%= contatoss.email %></td>
        <td><%= contatoss.dataNascimento %></td>
        <td><%= link_to 'Show', contatoss %></td>
        <td><%= link_to 'Edit', edit_contatoss_path(contatoss) %></td>
        <td><%= link_to 'Destroy', contatoss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contatoss', new_contatoss_path %>

app/views/contatosses/new.html.erb
<h1>New Contatoss</h1>

<%= render 'form', contatoss: @contatoss %>

<%= link_to 'Back', contatosses_path %>

app/views/contatosses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contatoss.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @contatoss.endereco %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contatoss.email %>
</p>

<p>
  <strong>Datanascimento:</strong>
  <%= @contatoss.dataNascimento %>
</p>

<%= link_to 'Edit', edit_contatoss_path(@contatoss) %> |
<%= link_to 'Back', contatosses_path %>